### ISSUE TITLE
All files are duplicated in the resulting .zip file

### ISSUE THREAD

**Issue by BeautyFades** [NotCoffee418/s3-zip-upload#10]
Hi 🫡
So, this might just be me being stupid, but whenever I use this action, the resulting .zip that is uploaded to S3 contains twice as many files as the source folder. Is this expected?

Here's some relevant info:
My workflow file:
```yaml
name: ZIP ETL Library and upload to S3
on:
  push:
    branches:
      - qa
      - prod
    paths:
      - somepath/lib/**

jobs:
  deploy-etl-lib-to-qa:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/qa'
    steps:
      - uses: actions/checkout@v2
      - name: QA - Update library ZIP on S3 
        uses: NotCoffee418/s3-zip-upload@v1.3
        env:
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_PATH: somepath/lib
          BUCKET_NAME: ${{ secrets.BUCKET_NAME}}
          DEST_FILE: lib/myzip.zip
          AWS_REGION: us-east-1
          SOURCE_MODE: ZIP
```
This properly zips the contents inside the ```SOURCE_PATH``` and uploads them to my S3 bucket at ```BUCKET_NAME/DEST_FILE``` (```mybucket/lib/myzip.zip```)

However, if I download that zip file and inspect its contents, it has two identical files for every file, as per image below:
![image](https://github.com/NotCoffee418/s3-zip-upload/assets/46428866/d37bff88-4ae8-496a-b0c1-bfd7b9fe7c35)

This also happens for the contents inside the ```dummysubpackage``` folder:
![image](https://github.com/NotCoffee418/s3-zip-upload/assets/46428866/4c99f6c7-90d1-485f-bafd-66fad0f88f60)

EDIT: this does not affect functionality, as the library works normally, I just found it weird lol

Any thoughts? And also, thanks for providing this!
